import 'dart:convert';
import 'dart:io';

import 'package:gps_pipeline/gps_pipeline.dart';
import 'package:test/test.dart';

// Wires the checked-in ground-truth fixtures (test/fixtures/synthetic_raw.ndjson
// / synthetic_truth.ndjson, generated by tool/synthetic_runner.dart) into an
// asserting dart test. Previously these fixtures were only consumed by
// tool/kalman_calibrate.dart, a manual CLI that prints deviation stats for a
// human to eyeball -- nothing in `dart test`/CI actually verified the
// pipeline's real-world accuracy against them.
void main() {
  final rawFile = File('test/fixtures/synthetic_raw.ndjson');
  final truthFile = File('test/fixtures/synthetic_truth.ndjson');

  final rawFixes = rawFile
      .readAsLinesSync()
      .where((l) => l.trim().isNotEmpty)
      .map((l) {
        final j = jsonDecode(l) as Map<String, dynamic>;
        return RawFix(
          lat: (j['lat'] as num).toDouble(),
          lng: (j['lng'] as num).toDouble(),
          elevation: (j['elevation'] as num).toDouble(),
          timestamp: DateTime.parse(j['timestamp'] as String),
          speedMps: (j['speedMps'] as num).toDouble(),
          accuracy: (j['accuracy'] as num).toInt(),
        );
      })
      .toList();

  final truth = truthFile
      .readAsLinesSync()
      .where((l) => l.trim().isNotEmpty)
      .map((l) {
        final j = jsonDecode(l) as Map<String, dynamic>;
        return (lat: (j['lat'] as num).toDouble(), lng: (j['lng'] as num).toDouble());
      })
      .toList();

  test('fixtures loaded and non-trivial (sanity check the test itself is exercising real data)', () {
    expect(rawFixes.length, greaterThan(100));
    expect(truth.length, greaterThan(100));
  });

  test(
    'the production Kalman configuration (ActivityProfile.run defaults) stays within a '
    'positional-accuracy budget against synthetic ground truth',
    () {
      final pipeline = GpsPipeline(profile: ActivityProfile.run);
      final results = <PipelineResult>[];
      for (final fix in rawFixes) {
        final res = pipeline.process(fix);
        if (res != null && res.isAccepted) results.add(res);
      }
      for (final res in pipeline.flush()) {
        if (res.isAccepted) results.add(res);
      }

      expect(results, isNotEmpty);

      final deviations = <double>[];
      for (final r in results) {
        final rLat = r.smoothedLat ?? r.raw.lat;
        final rLng = r.smoothedLng ?? r.raw.lng;
        double minDist = double.infinity;
        for (final t in truth) {
          final d = CoordinateUtil.haversineMetres(rLat, rLng, t.lat, t.lng);
          if (d < minDist) minDist = d;
        }
        deviations.add(minDist);
      }
      deviations.sort();

      final meanDev = deviations.reduce((a, b) => a + b) / deviations.length;
      final p95Dev = deviations[(deviations.length * 0.95).floor().clamp(0, deviations.length - 1)];
      final maxDev = deviations.last;

      // Baseline on this fixture as of this commit: mean 4.26m, p95 11.45m,
      // max 21.84m. Bounds below have real headroom over that baseline so
      // this catches a genuine regression (e.g. a bad Kalman constant
      // change) without being flaky over minor, harmless drift.
      expect(meanDev, lessThan(8.0));
      expect(p95Dev, lessThan(20.0));
      expect(maxDev, lessThan(35.0));
    },
  );

  test(
    'KNOWN ISSUE: filtered/smoothed cumulative distance overshoots ground-truth '
    'distance by a large margin on this fixture -- see DISCOVERED_ISSUES.md #7. '
    'Positional accuracy (see the test above) is good; this is specifically '
    'about summed point-to-point path length. Asserted as a loose upper bound '
    '(not a target) so this test still catches the pipeline getting *worse*, '
    'without pretending the current ~46% baseline is validated as correct.',
    () {
      double totalTruthDist = 0;
      for (int i = 0; i < truth.length - 1; i++) {
        totalTruthDist +=
            CoordinateUtil.haversineMetres(truth[i].lat, truth[i].lng, truth[i + 1].lat, truth[i + 1].lng);
      }

      final pipeline = GpsPipeline(profile: ActivityProfile.run);
      final results = <PipelineResult>[];
      for (final fix in rawFixes) {
        final res = pipeline.process(fix);
        if (res != null && res.isAccepted) results.add(res);
      }
      for (final res in pipeline.flush()) {
        if (res.isAccepted) results.add(res);
      }

      double filteredDist = 0;
      for (int i = 0; i < results.length - 1; i++) {
        filteredDist += CoordinateUtil.haversineMetres(
          results[i].smoothedLat ?? results[i].raw.lat,
          results[i].smoothedLng ?? results[i].raw.lng,
          results[i + 1].smoothedLat ?? results[i + 1].raw.lat,
          results[i + 1].smoothedLng ?? results[i + 1].raw.lng,
        );
      }

      final distErrPct = (filteredDist - totalTruthDist).abs() / totalTruthDist * 100.0;
      expect(distErrPct, lessThan(60.0)); // baseline observed: ~45.6%
    },
  );
}
